import type { Agency, Service } from '@/types';

export const SERVICE_CATEGORIES = [
  { value: 'identity', label: 'Identity Documents', icon: 'IdCard' },
  { value: 'travel', label: 'Travel & Passport', icon: 'Plane' },
  { value: 'business', label: 'Business Registration', icon: 'Briefcase' },
  { value: 'social-services', label: 'Social Services', icon: 'Heart' },
  { value: 'education', label: 'Education', icon: 'GraduationCap' },
  { value: 'healthcare', label: 'Healthcare', icon: 'Stethoscope' },
  { value: 'property', label: 'Property & Land', icon: 'Home' },
  { value: 'vehicle', label: 'Vehicle & LTO', icon: 'Car' },
  { value: 'tax', label: 'Tax & BIR', icon: 'Receipt' },
  { value: 'other', label: 'Other Services', icon: 'MoreHorizontal' },
] as const;

export const MOCK_AGENCIES: Agency[] = [
  {
    id: '1',
    slug: 'dfa',
    name: 'Department of Foreign Affairs',
    acronym: 'DFA',
    description: 'Handles passport applications and authentication of documents.',
    website: 'https://dfa.gov.ph',
  },
  {
    id: '2',
    slug: 'lto',
    name: 'Land Transportation Office',
    acronym: 'LTO',
    description: 'Regulates land transportation, licenses drivers, and registers vehicles.',
    website: 'https://lto.gov.ph',
  },
  {
    id: '3',
    slug: 'bir',
    name: 'Bureau of Internal Revenue',
    acronym: 'BIR',
    description: 'Administers and enforces internal revenue laws.',
    website: 'https://bir.gov.ph',
  },
  {
    id: '4',
    slug: 'psa',
    name: 'Philippine Statistics Authority',
    acronym: 'PSA',
    description: 'Issues birth, marriage, and death certificates and national IDs.',
    website: 'https://psa.gov.ph',
  },
  {
    id: '5',
    slug: 'sss',
    name: 'Social Security System',
    acronym: 'SSS',
    description: 'Provides social insurance programs for private sector workers.',
    website: 'https://sss.gov.ph',
  },
  {
    id: '6',
    slug: 'philhealth',
    name: 'Philippine Health Insurance Corporation',
    acronym: 'PhilHealth',
    description: 'Provides health insurance coverage and affordable healthcare.',
    website: 'https://philhealth.gov.ph',
  },
  {
    id: '7',
    slug: 'pagibig',
    name: 'Home Development Mutual Fund',
    acronym: 'Pag-IBIG',
    description: 'Provides housing loans and savings programs.',
    website: 'https://pagibigfund.gov.ph',
  },
  {
    id: '8',
    slug: 'nbi',
    name: 'National Bureau of Investigation',
    acronym: 'NBI',
    description: 'Issues NBI clearance certificates for employment and legal purposes.',
    website: 'https://nbi.gov.ph',
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: '1',
    slug: 'passport-new',
    title: 'New Passport Application',
    description: 'Apply for a new Philippine passport for travel abroad.',
    agencyId: '1',
    agency: MOCK_AGENCIES[0],
    category: 'travel',
    isFeatured: true,
    processingTime: '10-15 working days',
    totalFee: 950,
    tags: ['passport', 'travel', 'DFA'],
    requirements: [
      { id: 'r1', label: 'PSA Birth Certificate', description: 'Original and photocopy' },
      { id: 'r2', label: 'Valid Government ID', description: 'Any two valid IDs' },
      { id: 'r3', label: 'Accomplished Application Form', description: 'DFA Passport Application Form' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        title: 'Online Appointment',
        description: 'Book an appointment via DFA website',
        duration: '15 minutes',
      },
      {
        id: 's2',
        order: 2,
        title: 'Personal Appearance',
        description: 'Visit DFA office on your scheduled date',
        duration: '2-4 hours',
        fee: 950,
      },
      {
        id: 's3',
        order: 3,
        title: 'Biometrics & Photo',
        description: 'Have your biometrics and photo captured',
        duration: '30 minutes',
      },
      {
        id: 's4',
        order: 4,
        title: 'Receive Passport',
        description: 'Receive via courier or pick up',
        duration: '10-15 working days',
      },
    ],
  },
  {
    id: '2',
    slug: 'drivers-license-new',
    title: "New Driver's License",
    description: "Get your first Philippine driver's license from LTO.",
    agencyId: '2',
    agency: MOCK_AGENCIES[1],
    category: 'vehicle',
    isFeatured: true,
    processingTime: '1-3 working days',
    totalFee: 1000,
    tags: ['license', 'driving', 'LTO'],
    requirements: [
      { id: 'r1', label: 'Student Permit', description: 'Valid student permit' },
      { id: 'r2', label: 'Medical Certificate', description: 'From accredited clinic' },
      { id: 'r3', label: 'TIN Card or Number', description: 'Required for application' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Complete Student Permit', description: 'Hold student permit for required period' },
      { id: 's2', order: 2, title: 'Take Driving School', description: 'Complete NTSC-accredited driving school' },
      { id: 's3', order: 3, title: 'Written Exam', description: 'Pass the LTO written examination', fee: 200 },
      { id: 's4', order: 4, title: 'Practical Exam', description: 'Pass the driving skills test', fee: 200 },
      { id: 's5', order: 5, title: 'License Issuance', description: 'Pay fees and receive your license', fee: 600 },
    ],
  },
  {
    id: '3',
    slug: 'nbi-clearance',
    title: 'NBI Clearance',
    description: 'Obtain NBI clearance for employment, travel, or legal purposes.',
    agencyId: '8',
    agency: MOCK_AGENCIES[7],
    category: 'identity',
    isFeatured: true,
    processingTime: '1-3 working days',
    totalFee: 155,
    tags: ['NBI', 'clearance', 'background check'],
    requirements: [
      { id: 'r1', label: 'Valid Government ID', description: 'One primary or two secondary IDs' },
      { id: 'r2', label: 'Payment Receipt', description: 'Online payment confirmation' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        title: 'Online Registration',
        description: 'Register and fill out form at nbi-clearance.com',
      },
      { id: 's2', order: 2, title: 'Online Payment', description: 'Pay ₱155 via e-payment channels', fee: 155 },
      { id: 's3', order: 3, title: 'Appointment', description: 'Choose your preferred NBI branch and date' },
      { id: 's4', order: 4, title: 'Personal Appearance', description: 'Visit NBI with your IDs and receipt' },
      { id: 's5', order: 5, title: 'Receive Clearance', description: 'Clearance released same day or within 3 days' },
    ],
  },
  {
    id: '4',
    slug: 'psa-birth-certificate',
    title: 'PSA Birth Certificate',
    description: 'Request an official copy of your birth certificate from PSA.',
    agencyId: '4',
    agency: MOCK_AGENCIES[3],
    category: 'identity',
    isFeatured: true,
    processingTime: '3-5 working days',
    totalFee: 365,
    tags: ['PSA', 'birth certificate', 'civil registry'],
    requirements: [
      { id: 'r1', label: 'Valid ID', description: 'One government-issued ID' },
      { id: 'r2', label: 'Accomplished Request Form', description: 'PSA SERBILIS form' },
    ],
    steps: [
      {
        id: 's1',
        order: 1,
        title: 'Online Request',
        description: 'Request via PSA Serbilis website or physical office',
      },
      { id: 's2', order: 2, title: 'Payment', description: 'Pay ₱365 per copy', fee: 365 },
      { id: 's3', order: 3, title: 'Delivery', description: 'Receive via courier within 3-5 working days' },
    ],
  },
  {
    id: '5',
    slug: 'sss-membership',
    title: 'SSS Membership Registration',
    description: 'Register as an SSS member to access social insurance benefits.',
    agencyId: '5',
    agency: MOCK_AGENCIES[4],
    category: 'social-services',
    isFeatured: true,
    processingTime: '1-2 working days',
    totalFee: 0,
    tags: ['SSS', 'social security', 'membership'],
    requirements: [
      { id: 'r1', label: 'E1 Form', description: 'Personal Record form' },
      { id: 'r2', label: 'Birth Certificate', description: 'PSA-issued birth certificate' },
      { id: 'r3', label: 'Valid ID', description: 'Any government-issued ID' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Fill Out E1 Form', description: 'Accomplish the SSS Personal Record form' },
      { id: 's2', order: 2, title: 'Submit Requirements', description: 'Submit to any SSS branch' },
      { id: 's3', order: 3, title: 'Receive SS Number', description: 'Get your SS Number immediately' },
      { id: 's4', order: 4, title: 'Activate My.SSS', description: 'Register on My.SSS portal for online services' },
    ],
  },
  {
    id: '6',
    slug: 'philhealth-registration',
    title: 'PhilHealth Membership',
    description: 'Register for PhilHealth to access healthcare benefits.',
    agencyId: '6',
    agency: MOCK_AGENCIES[5],
    category: 'healthcare',
    isFeatured: true,
    processingTime: '1 working day',
    totalFee: 0,
    tags: ['PhilHealth', 'health insurance', 'membership'],
    requirements: [
      { id: 'r1', label: 'PMRF Form', description: 'PhilHealth Member Registration Form' },
      { id: 'r2', label: 'Two Valid IDs', description: 'Government-issued IDs' },
      { id: 'r3', label: '2x2 Photo', description: 'Recent ID photo' },
    ],
    steps: [
      { id: 's1', order: 1, title: 'Accomplish PMRF', description: 'Fill out PhilHealth Member Registration Form' },
      {
        id: 's2',
        order: 2,
        title: 'Submit to Branch',
        description: 'Submit form and requirements to any PhilHealth office',
      },
      {
        id: 's3',
        order: 3,
        title: 'Receive PhilHealth Number',
        description: 'Get your PhilHealth Identification Number (PIN)',
      },
    ],
  },
];

export const NAV_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/services', label: 'Services' },
  { href: '/agencies', label: 'Agencies' },
];

export const ADMIN_NAV_LINKS = [
  { href: '/admin', label: 'Dashboard', icon: 'LayoutDashboard' },
  { href: '/admin/services', label: 'Services', icon: 'FileText' },
  { href: '/admin/agencies', label: 'Agencies', icon: 'Building2' },
];
